import type { Metadata } from "next";
import {
    ClerkProvider,
    SignInButton,
    SignUpButton,
    SignedIn,
    SignedOut,
    UserButton, SignIn,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import CreatePDF from "@/components/CreatePDF";
import {Toaster} from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const bypass = (await cookies()).get("bypass")?.value;

    if (bypass === "true") {
        return (
            <ClerkProvider>
                <html lang="en">
                <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                {children}
                <Toaster richColors /> {/* 👈 Mount once at the root */}
                </body>
                </html>
            </ClerkProvider>
        );
    }

  return (
      <ClerkProvider
          signInUrl="/"
          signUpUrl="/sign-up"
      >
          <html lang="en">
          <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <header className="flex justify-end items-center p-4 gap-4 h-16">
              <SignedOut>
                  <SignInButton />
                  <SignUpButton>
                      <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                          Sign Up
                      </button>
                  </SignUpButton>
              </SignedOut>
              <SignedIn>
                  <CreatePDF />
                  <UserButton />
              </SignedIn>
          </header>

              {children}
              <Toaster richColors /> {/* 👈 Mount once at the root */}
          </body>
          </html>
      </ClerkProvider>
  );
}
